### ISSUE TITLE
Ability to override the config file name

### ISSUE THREAD

**Issue by pomek** [happo/happo-e2e#26]
The primary purpose of the issue is to give an integration an option to override the default config name.

Right now, it's hardcoded in the source code:

https://github.com/happo/happo-e2e/blob/f38a37dea558390cce65556755ca27e60f839c2b/src/loadHappoConfig.js#L5

I am trying to integrate an ESM/TypeScript project containing e2e tests (using Cypress).

When trying to run the entire setup, it ends with the following error:

```
Error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/root/path/.happo.js from /home/root/path/@root not supported.

.happo.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename .happo.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/root/path/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

As the proper, and the only (I think) solution is to rename the extension from `.js` to `.cjs`, the Happo integration does not understand it, as it forces using the `.js` extension.

I was able to hack the current package via the [`patch-package`](https://www.npmjs.com/package/patch-package) package that allows modifying files inside `node_modules/`. However, I am not happy with that.

I could try to create a PR containing the proposed changes. I would like to know if it will be accepted, and I appreciate any tips that will shorten the review process.

**Comment by trotzig** [comment]
There is a way to override the path to the config file using a `HAPPO_CONFIG_FILE` environment variable. Would that work for you? 

This is where that environment variable is used: https://github.com/happo/happo.io/blob/0cc7b7bc650c43037d12d8f7ffe5abdadcca010a/src/loadUserConfig.js#L53C23-L53C40

**Comment by pomek** [comment]
Hi @trotzig, thanks for the rapid response.

You're right, defining the env. variable helps.

```bash
HAPPO_CONFIG_FILE=./.happo.cjs yarn happo-e2e -- -- yarn test:cy:run
```

Loads the file I want to load instead of using the default one.

So, I think we can close the issue. Perhaps mentioning it somewhere in the docs would be helpful. OTOH, it could be already, but I missed it.

Anyway, thanks!

**Comment by trotzig** [comment]
I think this isn't mentioned so I'll make a note to update docs. Thanks for the report!
