### ISSUE TITLE
Handling Cypress tests without Happo screenshots while maintaining required CI checks

### ISSUE THREAD

**Issue by pudek357** [happo/happo-e2e#27]
Hey again!

We have the scenario in the monorepo where we run Cypress tests, but those tests don't have any `happoScreenshot` calls.
In such a scenario from each Cypress workflow we will get [[HAPPO] No snapshots were recorded. Ignoring](https://github.com/happo/happo-e2e/blob/c6b451de9e107cd2f4a6692d82e2389a03894443/bin/happo-e2e.js#L149).

We cannot call `happo-e2e finalize --skippedExamples` with all skipped examples as you early return in
```tsx
  if (!allRequestIds.size) {
    console.log(`[HAPPO] No snapshots were recorded. Ignoring.`);
    return;
  }
```

and we get:
```
Failed POST https://happo.io/api/async-reports/abc/finalize. Retrying...
Error: Request to POST https://happo.io/api/async-reports/..
..
  statusCode: 404
}
```

At the point when we call `happo-e2e finalize` (with or without `--skippedExamples` argument) we know if all examples equal skipped examples, so I wanted to introduce such logic in our codebase:
```
if (allScreenshots.length === skippedScreenshots.length) {
  console.log(
    'Number of skipped screenshots is equal to the total number of screenshots. Skipping.'
  )

  process.exit(0)
}

..
execSync(`yarn happo-e2e finalize --skippedExamples '${stringifiedSkippedSceenshots}'`, { encoding: 'utf-8' })
```

But then we realized that we cannot omit running `happo-e2e finalize` as we want to keep CI check required:
![image](https://github.com/happo/happo-e2e/assets/4816942/97b9c3fb-4c9d-437c-8715-9fbf771a0cb1)

Do you see any solution for that? Thank you!

**Comment by trotzig** [comment]
Hi @pudek357!

I think you can use the "Skip" API endpoint here. 
https://happo.io/docs/api#skip

Let me know if that doesn't cover your use case.

**Comment by pudek357** [comment]
@trotzig yes. This is what I was looking for.

But it would significantly streamline our development process to have a built-in Yarn command for Happo, such as `yarn happo-e2e --skip`.
This addition would eliminate the need for custom scripts or manual intervention.

**Comment by pudek357** [comment]
We ended up to use https://happo.io/docs/api#skip
Thank you!
