### ISSUE TITLE
Happo e2e version 3.1.0 increases the execution time of the Happo Tests

### ISSUE THREAD

**Issue by sankar-refined** [happo/happo-e2e#46]
Hi,

We have been using Happo as part of our visual regression testing tool. We have been using it for over a year now.

Recently I tried updating the happo-e2e package from  version 2.4.1 to version 3.1.0.

I could see that the execution time for the  happo tests have increased from 6 minutes to 21 minutes.

We are not sure of what is the problem, but here are our observations.

with 2.4.1, we get the output of [happo] > testname (20 seconds)
we get 404  failed to fetch url errors, but they are printed as a single line (they are as designed and as expected)

But with 3.1.0,  we get a more extensive output from Happo,

- debug output from controller,
- downloading the css 
- creating asset package from urls (from more than 500+ items)
- fetching asset from urls
- fetching Happo raw environment
- resolved environment

(here it starts the actual happo tests)

- controller init print messages
- downloading the css
- creating asset package from urls (from more than 1900 items)
- fetching the asset
- we get failed to fetch 404 errors, but we get a more detailed output, which also includes retries

From my observation, There are too much information printed on the bitbucket console. and that increases the execution time for the Happo tests that we have in the pipeline. ( that 1 line printout in 2.4.1 prints out over 1400 lines of output on bitbucket in 3.1.0 version)

**Comment by lencioni** [comment]
Hello @sankar-refined! I'm sorry to hear that you are seeing some performance issues when updating your happo-e2e package. Going from 6 minutes to 21 minutes is quite the change! Thank you for reaching out! I'd like to help get this resolved for you.

It looks like there were a few releases between 2.4.1 and 3.1.0. Would it be possible for you to narrow down the issue to a more specific version? That will help us pinpoint the issue.

Also, are you changing anything else at the same time or have you already isolated the happo-e2e package. I just want to make sure that we are looking at the right thing before we dig too deeply.

**Comment by sankar-refined** [comment]
The issue starts version 2.6.0. It is from this version, we are seeing the performance issue.

**Comment by lencioni** [comment]
Thanks for narrowing that down! Here are all of the changes between 2.5.0 and 2.6.0: https://github.com/happo/happo-e2e/compare/v2.5.0...v2.6.0

It looks like it is just 2 small PRs:

- https://github.com/happo/happo-e2e/pull/31
- https://github.com/happo/happo-e2e/pull/29

I'm wondering if we can narrow it down to one of these specific changes. Do you happen to be using `<canvas>` at all? If not, then we can easily rule out #29. I'm wondering if this happened because of #31 and you have some stylesheets that were not previously correctly resolved?

**Comment by sankar-refined** [comment]
The exact version is 2.6.1., that causes this performance issue. (We are using the "happo-e2e": "~2.6.0", which means it also includes the minor versions released)

It took some time for me to narrow it down to the PR: https://github.com/happo/happo-e2e/pull/36 

`let res;
      try {
        res = await proxiedFetch(absUrl, { retryCount: 5 });
      } catch (e) {`

**Comment by lencioni** [comment]
Ah! That makes more sense to me. Thanks for figuring that out.

Do you happen to have a lot of requests for CSS files? And I'm curious if they are succeeding or if they are always failing and being retried repeatedly? Also, are the same URLs being requested and retried repeatedly, or are they always different URLs?

**Comment by sankar-refined** [comment]
We have both CSS and Images requests. But mostly, images makes the most requests. 

Happo does not have any permissions to access those images. We get not found and unauthorised errors for images and not found for the css. Below is the output from our pipelines.

With Version 2.4.1 -> this is the output for images and css

> ✓  1 [happo] › test/_happo-set/e2e-set/admin/site-builder-happo.spec.ts:9:5 › site builder @r-happo @happoPlaywright (22.0s)
> [HAPPO] Failed to fetch url https://local-charlie-tests.refined.site/images/db43d7b2-c64e-46d1-9377-3d8c1c5cec83 — Not Found
> [HAPPO] Failed to fetch url https://local-charlie-tests.refined.site/download/thumbnails/592609289/purple%20-%20background.png?version=1&modificationDate=1673263082732&cacheVersion=1&api=v2 — 
> Unauthorized
> [HAPPO] Failed to fetch url https://aui-cdn.atlassian.com/aui-adg/5.10.1/css/clear.svg — Not Found

with version 3.1.0 -> this is the output for images and css (this does not include the async retries)

> ✓  1 [happo] › test/_happo-set/e2e-set/admin/site-builder-happo.spec.ts:9:5 › site builder @r-happo @happoPlaywright (26.6s)
> [HAPPO] Failed fetching https://local-charlie-tests.refined.site/images/db43d7b2-c64e-46d1-9377-3d8c1c5cec83. Retrying...
> Error: [HAPPO] Request to https://local-charlie-tests.refined.site/images/db43d7b2-c64e-46d1-9377-3d8c1c5cec83 failed: 404 - {"status":404,"message":"Not Found"}
>     at asyncRetry.retries [90m(/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/fetch.js:21:19[90m)[39m
> [90m    at processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
>     at [90m/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/createAssetPackage.js:115:28
>     at async Promise.all (index 23)
>     at [90m/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/createAssetPackage.js:139:5 {
>   statusCode: [33m404[39m
> }

> [HAPPO] Failed fetching https://local-charlie-tests.refined.site/download/thumbnails/592609289/purple%20-%20background.png?version=1&modificationDate=1673263082732&cacheVersion=1&api=v2. Retrying...
> Error: [HAPPO] Request to https://local-charlie-tests.refined.site/download/thumbnails/592609289/purple%20-%20background.png?version=1&modificationDate=1673263082732&cacheVersion=1&api=v2 failed: 401 - {"status":401,"message":"You need to log in"}
>     at asyncRetry.retries [90m(/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/fetch.js:21:19[90m)[39m
> [90m    at processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
>     at [90m/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/createAssetPackage.js:115:28
>     at async Promise.all (index 6)
>     at [90m/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/createAssetPackage.js:139:5 {
>   statusCode: [33m401[39m
> }

> [HAPPO] Failed fetching https://aui-cdn.atlassian.com/aui-adg/5.10.1/css/clear.svg. Retrying...
> Error: [HAPPO] Request to https://aui-cdn.atlassian.com/aui-adg/5.10.1/css/clear.svg failed: 404 - <html>
> <head><title>404 Not Found</title></head>
> <body>
> <h1>404 Not Found</h1>
> <ul>
> <li>Code: NoSuchKey</li>
> <li>Message: The specified key does not exist.</li>
> <li>Key: aui-adg/5.10.1/css/clear.svg</li>
> <li>RequestId: 0ZWK0PH4JZG0V64R</li>
> <li>HostId: aUbKNwE8sA/zhe5SJyCkJ4SjYV1W+VDOahy6XEBoNx3CGJ48Ab8hPkRK10xhSvHcrnpF3/mP1DRGyHe6LWfs6n5P16JNde7o6QuoMdSAXl0=</li>
> </ul>
> <h3>An Error Occurred While Attempting to Retrieve a Custom Error Document</h3>
> <ul>
> <li>Code: NoSuchKey</li>
> <li>Message: The specified key does not exist.</li>
> <li>Key: error.html</li>
> </ul>
> <hr/>
> </body>
> </html>
> 
>     at asyncRetry.retries [90m(/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/fetch.js:21:19[90m)[39m
> [90m    at processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
>     at [90m/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/createAssetPackage.js:115:28
>     at async Promise.all (index 49)
>     at [90m/opt/atlassian/pipelines/agent/build/[39mnode_modules/[4mhappo-e2e[24m/src/createAssetPackage.js:139:5 {
>   statusCode: [33m404[39m
> }

NOTES: We use HAPPO_DOWNLOAD_ALL = true in our bitbucket. disabling them for 3.1.0, decreases the execution time, but it still twice the normal execution time.

**Comment by lencioni** [comment]
Thank you, this is helpful. I think it would be good to avoid retrying for 4xx status codes. I'll work on a PR for that now.

**Comment by lencioni** [comment]
@sankar-refined I've published v3.1.1 with this fix now. Can you try it out and let me know if it helps or if there's still more we can do?

**Comment by lencioni** [comment]
@sankar-refined I just wanted to let you know that I found another thing that might help you and published v3.1.2 with the improvement.

**Comment by sankar-refined** [comment]
Thank you for the fix. The fix works as intended.

**Comment by lencioni** [comment]
Thanks so much for the report! I'm glad we could get this sorted out for you.
